# Generated by Django 5.1.3 on 2024-12-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Email', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('Mobile', models.IntegerField()),
                ('Degree', models.CharField(max_length=10)),
            ],
        ),
    ]
