# Generated by Django 5.1.3 on 2025-10-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
