# Generated by Django 5.1.3 on 2025-10-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodapp', '0002_data_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.IntegerField()),
                ('product_picture', models.ImageField(blank=True, upload_to='')),
                ('product_details', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='data',
        ),
    ]
