# Generated by Django 5.1.3 on 2025-10-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodapp', '0005_alter_products_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
