# Generated by Django 5.1.3 on 2025-10-09 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foodapp', '0007_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
