# Generated by Django 5.1.3 on 2024-12-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapplication', '0002_remove_datas_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='Age',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='datas',
            name='Degree',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='datas',
            name='Email',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='datas',
            name='Mobile',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='datas',
            name='Name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='datas',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
    ]
